# Generated by Django 2.1.5 on 2019-03-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routemanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_text',
        ),
        migrations.AddField(
            model_name='address',
            name='address_one',
            field=models.CharField(default='home', max_length=200, verbose_name='Address Line 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='address_two',
            field=models.CharField(default='home', max_length=200, verbose_name='Address Line 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='city_name',
            field=models.CharField(default='home', max_length=50, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='state_abbr',
            field=models.CharField(default='home', max_length=3, verbose_name='State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='home', max_length=10, verbose_name='Zip'),
            preserve_default=False,
        ),
    ]
