# Generated by Django 2.1.5 on 2019-03-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routemanager', '0003_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='safety_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
