# Generated by Django 2.1.5 on 2019-03-14 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routemanager', '0005_address_spot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
